apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f htpc.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f htpc.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-gitops-default: "true"
        io.kompose.service: radarr
    spec:
      containers:
        - env:
            - name: PGID
            - name: PUID
            - name: TZ
          image: linuxserver/radarr:latest
          name: radarr
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: radarr-claim0
              readOnly: true
            - mountPath: /config
              name: radarr-claim1
            - mountPath: /movies
              name: radarr-claim2
            - mountPath: /downloads
              name: radarr-claim3
      restartPolicy: Always
      volumes:
        - name: radarr-claim0
          persistentVolumeClaim:
            claimName: radarr-claim0
            readOnly: true
        - name: radarr-claim1
          persistentVolumeClaim:
            claimName: radarr-claim1
        - name: radarr-claim2
          persistentVolumeClaim:
            claimName: radarr-claim2
        - name: radarr-claim3
          persistentVolumeClaim:
            claimName: radarr-claim3
status: {}
