apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f htpc.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: plex-server
  name: plex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plex-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f htpc.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-gitops-default: "true"
        io.kompose.service: plex-server
    spec:
      containers:
        - env:
            - name: TZ
          image: plexinc/pms-docker:latest
          name: plex-server
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: plex-server-claim0
            - mountPath: /transcode
              name: plex-server-claim1
            - mountPath: /data
              name: plex-server-claim2
      restartPolicy: Always
      volumes:
        - name: plex-server-claim0
          persistentVolumeClaim:
            claimName: plex-server-claim0
        - name: plex-server-claim1
          persistentVolumeClaim:
            claimName: plex-server-claim1
        - name: plex-server-claim2
          persistentVolumeClaim:
            claimName: plex-server-claim2
status: {}
